### ISSUE TITLE
enclient.rb exited abnormally with code 1

### ISSUE THREAD

**Issue by cocodrino** [pymander/evernote-mode#15]
Hi, I've installed emacs24 and ruby 1.8.7 (2011-06-30 patchlevel 352) [x86_64-linux] I install evernote from melpa but when I try enter in the evernote mode I get this error....

I don't know it the problem can be caused by the ruby version, I don't know much about ruby but when I type whereis ruby I get this

ruby: /usr/bin/ruby /usr/bin/ruby1.8 /usr/lib/ruby /usr/bin/X11/ruby /usr/bin/X11/ruby1.8 /usr/share/man/man1/ruby.1.gz

although when I type ruby -v I get the first ruby version commented before ruby 1.8.7

can you know how fixed it?? thanks!!!

error in process sentinel: enh-command-sentinel: enclient.rb exited abnormally with code 1
/usr/local/lib/site_ruby/1.8/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require': no such file to load -- user_store_types (LoadError)
	from /usr/local/lib/site_ruby/1.8/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/gems/1.8/gems/evernote-thrift-1.25.1/lib/Evernote/EDAM/user_store.rb:8
	from /usr/local/lib/site_ruby/1.8/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require'
	from /usr/local/lib/site_ruby/1.8/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/bin/enclient.rb:43

error in process sentinel: enclient.rb exited abnormally with code 1
/usr/local/lib/site_ruby/1.8/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require': no such file to load -- user_store_types (LoadError)
	from /usr/local/lib/site_ruby/1.8/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/gems/1.8/gems/evernote-thrift-1.25.1/lib/Evernote/EDAM/user_store.rb:8
	from /usr/local/lib/site_ruby/1.8/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require'
	from /usr/local/lib/site_ruby/1.8/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/bin/enclient.rb:43

byte-code: Beginning of buffer

**Comment by pymander** [comment]
Since we aren't going to support Ruby 1.8, I'm closing this for now. Let me know if it still happens after upgrading to Ruby 1.9.
