### ISSUE TITLE
Issues with newer versions of ruby

### ISSUE THREAD

**Issue by benquike** [pymander/evernote-mode#30]
When using ruby 2.2.1, the following issue occurs during the installation stage

setup.rb:788:in `load_rbconfig': uninitialized constant Config (NameError)
        from setup.rb:768:in `invoke'
        from setup.rb:1578:in `<main>'

**Comment by pymander** [comment]
I don't have any plans at the moment to support newer versions of Ruby. If you'd like to contribute fixes, however, I would welcome them.
