### ISSUE TITLE
Can't install on windows

### ISSUE THREAD

**Issue by cclinton** [pymander/evernote-mode#31]
Running ruby setup.rb on Windows 8.1 x64 yields:

setup.rb:283: warning: duplicated key at line 284 ignored: "bin-dir"
setup.rb:788:in `load_rbconfig': uninitialized constant Config (NameError)
        from setup.rb:768:in `invoke'
        from setup.rb:1578:in `<main>'

ruby -v  
ruby 2.2.2p95 (2015-04-13 revision 50295) [x64-mingw32]

**Comment by pymander** [comment]
Let me know if this is still broken.
