### ISSUE TITLE
enclient.rb exits due to syntax error

### ISSUE THREAD

**Issue by ferdy** [pymander/evernote-mode#6]
i got this message on *Message* buffer as soon as i call evernote-browser.
got the same error calling enclient.rb from cli.

[ evernote.el cloned by github on MacOSX Mavericks with emacs 24.3.2, ruby 1.8.7 and gem 1.3.7 with evernote-thrift (1.25.1), evernote_oauth (0.2.2), oauth (0.4.7) (from macports 2.2.1)]

-=-=-=

Error in process sentinel: enclient.rb exited abnormally with code 1
/opt/local/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': /opt/local/lib/ruby/gems/1.8/gems/evernote_oauth-0.2.2/lib/evernote/edam/type/resource.rb:17: odd number list for Hash (SyntaxError)
            with_content: false,
                         ^
/opt/local/lib/ruby/gems/1.8/gems/evernote_oauth-0.2.2/lib/evernote/edam/type/resource.rb:17: syntax error, unexpected ':', expecting '}'
            with_content: false,
                         ^
/opt/local/lib/ruby/gems/1.8/gems/evernote_oauth-0.2.2/lib/evernote/edam/type/resource.rb:17: Can't assign to false
/opt/local/lib/ruby/gems/1.8/gems/evernote_oauth-0.2.2/lib/evernote/edam/type/resource.rb:18: syntax error, unexpected ':', expecting '='
            with_resources_data: false,
                                ^
/opt/local/lib/ruby/gems/1.8/gems/evernote_oauth-0.2.2/lib/evernote/edam/type/resource.rb:18: Can't assign to false
/opt/local/lib/ruby/gems/1.8/gems/evernote_oauth-0.2.2/lib/evernote/edam/type/resource.rb:19: syntax error, unexpected ':', expecting '='
            with_resources_recognition: false,
                                       ^
/opt/local/lib/ruby/gems/1.8/gems/evernote_oauth-0.2.2/lib/evernote/edam/type/resource.rb:19: Can't assign to false
/opt/local/lib/ruby/gems/1.8/gems/evernote_oauth-0.2.2/lib/evernote/edam/type/resource.rb:20: syntax error, unexpected ':', expecting '='
            with_resources_alternate_data: false
                                          ^
	from /opt/local/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:31:in `require'
	from /opt/local/lib/ruby/gems/1.8/gems/evernote_oauth-0.2.2/lib/evernote_types.rb:6
	from /opt/local/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
	from /opt/local/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:31:in `require'
	from /opt/local/lib/ruby/gems/1.8/gems/evernote_oauth-0.2.2/lib/evernote_oauth.rb:6
	from /opt/local/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
	from /opt/local/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `require'
	from /opt/local/bin/enclient.rb:44

**Comment by pymander** [comment]
Since we don't try to support Ruby 1.8, I'm going to close this issue for now. Let me know if it's still a problem.
